spring.application.name=esg-residuos

# Recriar o schema a cada inicialização
spring.jpa.hibernate.ddl-auto=create-drop

# Configurações do Flyway para limpar o banco a cada startup
spring.flyway.clean-on-validation-error=true
spring.flyway.clean-disabled=false
