spring.application.name=esg-residuos

spring.jpa.hibernate.ddl-auto=create-drop

spring.flyway.clean-on-validation-error=true
spring.flyway.clean-disabled=false

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.hikari.maximum-pool-size=${SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE:10}